# Semana 4 — Taller práctico: funciones, modularización y GitHub

**Asignatura:** Análisis de Datos con Python  
**Tipo de evidencia:** Notebook con ejercicios resueltos + repositorio inicial en GitHub  

## Propósito del taller

Aplicar funciones, modularización básica, comprensión de listas y diccionarios, manejo de errores y buenas prácticas de programación en un caso sencillo de análisis de datos.

## Entregables

1. Notebook completo con los ejercicios resueltos.
2. Repositorio inicial en GitHub con estructura organizada.
3. Archivo `README.md` con descripción del repositorio.
4. Evidencia del enlace al repositorio en la última sección del notebook.

## Instrucciones

Complete las celdas marcadas con `TODO`.

In [5]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
datos = pd.read_csv("/content/drive/MyDrive/ANALISIS_DE_DATOS/mecatronics_dataset.csv")
datos.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   time  temperature_C  vibration_g  current_A system_state
0     0      20.397371     0.709903   1.932482       normal
1     1      19.989382     0.638695   1.995546       normal
2     2      20.718098     0.508945   1.940743       normal
3     3      21.518244     0.402959   1.999154       normal
4     4      20.212251     0.604733   1.850520       normal

## Parte 1 — Función para convertir valores

Cree una función llamada `convertir_a_float(valor)` que intente convertir un valor a número decimal.

La función debe retornar:

- El número convertido, si la conversión es posible.
- `None`, si el valor no se puede convertir.

In [6]:
# TODO: cree la función convertir_a_float

def convertir_a_float(valor):
  try:
     return float(valor)
  except (ValueError, TypeError):
        return None
print(convertir_a_float("12.5"))
print(convertir_a_float("8.75"))
print(convertir_a_float("3.14"))
print(convertir_a_float("error"))
print(convertir_a_float("Karen"))
print(convertir_a_float(""))
print(convertir_a_float(None))

12.5
8.75
3.14
None
None
None
None

## Parte 2 — Función para calcular potencia

Cree una función llamada `calcular_potencia(voltaje, corriente)`.

La función debe:

- Retornar `None` si voltaje o corriente son `None`.
- Retornar `None` si voltaje o corriente son negativos.
- Retornar `voltaje * corriente` en los demás casos.

In [7]:
# TODO: cree la función calcular_potencia
def calcular_potencia(voltaje, corriente):
  if voltaje is None or corriente is None:
      return None
  elif voltaje < 0 or corriente <0:
      return None
  else:
      return voltaje * corriente
print(calcular_potencia(5, 3))
print(calcular_potencia(12, 2))
print(calcular_potencia(None, 2))
print(calcular_potencia(12, -1))
print(calcular_potencia(None, None))
print(calcular_potencia(-12, 1))

15
24
None
None
None
None

## Parte 3 — Función para clasificar temperatura

Cree una función llamada `clasificar_temperatura(temp)` con los siguientes criterios:

- Si `temp` es `None`: `"Dato inválido"`
- Si `temp < 40`: `"Normal"`
- Si `40 <= temp < 50`: `"Precaución"`
- Si `temp >= 50`: `"Alerta"`

In [8]:
# TODO: cree la función clasificar_temperatura
def clasificar_temperatura(temp):
  if temp is None:
    return "Dato inválido"
  elif temp < 40:
    return "Normal"
  elif temp < 50:
    return "Precaución"
  else:
    return "Alerta"
print(clasificar_temperatura(35))
print(clasificar_temperatura(45))
print(clasificar_temperatura(52))
print(clasificar_temperatura(52.5))
print(clasificar_temperatura(None))

Normal
Precaución
Alerta
Alerta
Dato inválido

## Parte 4 — Limpieza y procesamiento de registros

Procese la lista `registros_crudos` y cree una nueva lista llamada `registros_limpios`.

Cada registro limpio debe contener:

- `id`
- `voltaje`
- `corriente`
- `temperatura`
- `potencia`
- `estado_temperatura`

Use las funciones creadas.

In [9]:
VOLTAJE_NOMINAL = 24.0  # <-- cambia esto al voltaje real de tu sistema
registros_crudos = [
    {
        "id": int(fila["time"]),
        "voltaje": VOLTAJE_NOMINAL,
        "corriente": fila["current_A"],
        "temperatura": fila["temperature_C"],
    }
    for _, fila in datos.iterrows()
]

registros_limpios = [
    {
        "id": reg["id"],
        "voltaje": convertir_a_float(reg["voltaje"]),
        "corriente": convertir_a_float(reg["corriente"]),
        "temperatura": convertir_a_float(reg["temperatura"]),
        "potencia": calcular_potencia(convertir_a_float(reg["voltaje"]), convertir_a_float(reg["corriente"]),),
        "estado_temperatura": clasificar_temperatura(convertir_a_float(reg["temperatura"])),
    }
    for reg in registros_crudos
]
print(registros_limpios)

[{'id': 0, 'voltaje': 24.0, 'corriente': 1.9324821725025616, 'temperatura': 20.397371322408983, 'potencia': 46.37957214006148, 'estado_temperatura': 'Normal'}, {'id': 1, 'voltaje': 24.0, 'corriente': 1.9955462811794744, 'temperatura': 19.98938189252972, 'potencia': 47.893110748307386, 'estado_temperatura': 'Normal'}, {'id': 2, 'voltaje': 24.0, 'corriente': 1.9407431963770216, 'temperatura': 20.718097501413723, 'potencia': 46.57783671304852, 'estado_temperatura': 'Normal'}, {'id': 3, 'voltaje': 24.0, 'corriente': 1.9991538720301445, 'temperatura': 21.51824391752364, 'potencia': 47.979692928723466, 'estado_temperatura': 'Normal'}, {'id': 4, 'voltaje': 24.0, 'corriente': 1.8505201200913155, 'temperatura': 20.212250770067197, 'potencia': 44.41248288219157, 'estado_temperatura': 'Normal'}, {'id': 5, 'voltaje': 24.0, 'corriente': 2.0710982105453186, 'temperatura': 20.311857517674795, 'potencia': 49.70635705308764, 'estado_temperatura': 'Normal'}, {'id': 6, 'voltaje': 24.0, 'corriente': 2.059721346774741, 'temperatura': 21.86193128885051, 'potencia': 49.433312322593785, 'estado_temperatura': 'Normal'}, {'id': 7, 'voltaje': 24.0, 'corriente': 1.9876576785834703, 'temperatura': 21.31166335654351, 'potencia': 47.703784286003284, 'estado_temperatura': 'Normal'}, {'id': 8, 'voltaje': 24.0, 'corriente': 2.144979784186301, 'temperatura': 20.42101152432327, 'potencia': 51.47951482047122, 'estado_temperatura': 'Normal'}, {'id': 9, 'voltaje': 24.0, 'corriente': 2.182413075761058, 'temperatura': 21.329195901997892, 'potencia': 52.377913818265384, 'estado_temperatura': 'Normal'}, {'id': 10, 'voltaje': 24.0, 'corriente': 1.937402422601948, 'temperatura': 20.62261249972533, 'potencia': 46.49765814244675, 'estado_temperatura': 'Normal'}, {'id': 11, 'voltaje': 24.0, 'corriente': 2.031279223421964, 'temperatura': 20.718564312548143, 'potencia': 48.75070136212714, 'estado_temperatura': 'Normal'}, {'id': 12, 'voltaje': 24.0, 'corriente': 2.0399112677138653, 'temperatura': 21.382082949388497, 'potencia': 48.95787042513277, 'estado_temperatura': 'Normal'}, {'id': 13, 'voltaje': 24.0, 'corriente': 2.031979199900255, 'temperatura': 19.75477856373454, 'potencia': 48.767500797606125, 'estado_temperatura': 'Normal'}, {'id': 14, 'voltaje': 24.0, 'corriente': 2.2179210483599747, 'temperatura': 20.001843976810143, 'potencia': 53.2301051606394, 'estado_temperatura': 'Normal'}, {'id': 15, 'voltaje': 24.0, 'corriente': 2.1244450477039805, 'temperatura': 21.02777100991392, 'potencia': 50.98668114489553, 'estado_temperatura': 'Normal'}, {'id': 16, 'voltaje': 24.0, 'corriente': 2.126070481148329, 'temperatura': 20.76256790681305, 'potencia': 51.0256915475599, 'estado_temperatura': 'Normal'}, {'id': 17, 'voltaje': 24.0, 'corriente': 1.960660579377513, 'temperatura': 21.91883332678029, 'potencia': 47.05585390506031, 'estado_temperatura': 'Normal'}, {'id': 18, 'voltaje': 24.0, 'corriente': 2.232934545039433, 'temperatura': 21.034951905958483, 'potencia': 53.59042908094639, 'estado_temperatura': 'Normal'}, {'id': 19, 'voltaje': 24.0, 'corriente': 2.053624632002278, 'temperatura': 20.72475938599668, 'potencia': 49.286991168054676, 'estado_temperatura': 'Normal'}, {'id': 20, 'voltaje': 24.0, 'corriente': 2.1915042039475536, 'temperatura': 23.11961072668049, 'potencia': 52.596100894741284, 'estado_temperatura': 'Normal'}, {'id': 21, 'voltaje': 24.0, 'corriente': 2.2210029999671264, 'temperatura': 21.85818122490862, 'potencia': 53.30407199921103, 'estado_temperatura': 'Normal'}, {'id': 22, 'voltaje': 24.0, 'corriente': 2.336870811659005, 'temperatura': 22.18371988908034, 'potencia': 56.08489947981612, 'estado_temperatura': 'Normal'}, {'id': 23, 'voltaje': 24.0, 'corriente': 2.077239462111825, 'temperatura': 21.079941985856838, 'potencia': 49.8537470906838, 'estado_temperatura': 'Normal'}, {'id': 24, 'voltaje': 24.0, 'corriente': 1.9132556116877744, 'temperatura': 21.87338969808727, 'potencia': 45.91813468050658, 'estado_temperatura': 'Normal'}, {'id': 25, 'voltaje': 24.0, 'corriente': 2.240438010434181, 'temperatura': 22.485865764788908, 'potencia': 53.77051225042034, 'estado_temperatura': 'Normal'}, {'id': 26, 'voltaje': 24.0, 'corriente': 2.4087037000252374, 'temperatura': 21.56360582728084, 'potencia': 57.8088888006057, 'estado_temperatura': 'Normal'}, {'id': 27, 'voltaje': 24.0, 'corriente': 2.3588927081821884, 'temperatura': 22.871238372942106, 'potencia': 56.61342499637252, 'estado_temperatura': 'Normal'}, {'id': 28, 'voltaje': 24.0, 'corriente': 2.262048420635786, 'temperatura': 22.17542003766937, 'potencia': 54.28916209525886, 'estado_temperatura': 'Normal'}, {'id': 29, 'voltaje': 24.0, 'corriente': 2.197735422145771, 'temperatura': 22.506764684124747, 'potencia': 52.74565013149851, 'estado_temperatura': 'Normal'}, {'id': 30, 'voltaje': 24.0, 'corriente': 2.3331535551061, 'temperatura': 22.34184707719166, 'potencia': 55.9956853225464, 'estado_temperatura': 'Normal'}, {'id': 31, 'voltaje': 24.0, 'corriente': 2.160348465847411, 'temperatura': 24.38699835029368, 'potencia': 51.848363180337856, 'estado_temperatura': 'Normal'}, {'id': 32, 'voltaje': 24.0, 'corriente': 2.310314342878629, 'temperatura': 22.97517942702161, 'potencia': 55.4475442290871, 'estado_temperatura': 'Normal'}, {'id': 33, 'voltaje': 24.0, 'corriente': 2.317909223935093, 'temperatura': 22.219415516702448, 'potencia': 55.62982137444223, 'estado_temperatura': 'Normal'}, {'id': 34, 'voltaje': 24.0, 'corriente': 2.3777697992291023, 'temperatura': 23.80200104977489, 'potencia': 57.066475181498454, 'estado_temperatura': 'Normal'}, {'id': 35, 'voltaje': 24.0, 'corriente': 2.5517994976672345, 'temperatura': 22.24441351621164, 'potencia': 61.24318794401363, 'estado_temperatura': 'Normal'}, {'id': 36, 'voltaje': 24.0, 'corriente': 2.3188533225080445, 'temperatura': 23.46401423586117, 'potencia': 55.65247974019307, 'estado_temperatura': 'Normal'}, {'id': 37, 'voltaje': 24.0, 'corriente': 2.2321829443037102, 'temperatura': 21.803703459036903, 'potencia': 53.57239066328904, 'estado_temperatura': 'Normal'}, {'id': 38, 'voltaje': 24.0, 'corriente': 2.2836749532986658, 'temperatura': 22.38205838643401, 'potencia': 54.808198879167975, 'estado_temperatura': 'Normal'}, {'id': 39, 'voltaje': 24.0, 'corriente': 2.112159865136246, 'temperatura': 23.67388608469735, 'potencia': 50.691836763269905, 'estado_temperatura': 'Normal'}, {'id': 40, 'voltaje': 24.0, 'corriente': 2.222110057300088, 'temperatura': 24.177553718493943, 'potencia': 53.33064137520211, 'estado_temperatura': 'Normal'}, {'id': 41, 'voltaje': 24.0, 'corriente': 2.2528430920780376, 'temperatura': 23.792823773586456, 'potencia': 54.0682342098729, 'estado_temperatura': 'Normal'}, {'id': 42, 'voltaje': 24.0, 'corriente': 2.2432260792030787, 'temperatura': 23.630696973943703, 'potencia': 53.83742590087389, 'estado_temperatura': 'Normal'}, {'id': 43, 'voltaje': 24.0, 'corriente': 2.31240553647776, 'temperatura': 23.548329858004955, 'potencia': 55.49773287546624, 'estado_temperatura': 'Normal'}, {'id': 44, 'voltaje': 24.0, 'corriente': 2.216133027942297, 'temperatura': 22.670876802200908, 'potencia': 53.18719267061513, 'estado_temperatura': 'Normal'}, {'id': 45, 'voltaje': 24.0, 'corriente': 2.4113515627136635, 'temperatura': 23.34075918142165, 'potencia': 57.87243750512792, 'estado_temperatura': 'Normal'}, {'id': 46, 'voltaje': 24.0, 'corriente': 2.2998102097306097, 'temperatura': 23.609497083414, 'potencia': 55.19544503353463, 'estado_temperatura': 'Normal'}, {'id': 47, 'voltaje': 24.0, 'corriente': 2.299067409775858, 'temperatura': 24.883488283000705, 'potencia': 55.17761783462059, 'estado_temperatura': 'Normal'}, {'id': 48, 'voltaje': 24.0, 'corriente': 2.26708260926116, 'temperatura': 24.37085247315976, 'potencia': 54.40998262226784, 'estado_temperatura': 'Normal'}, {'id': 49, 'voltaje': 24.0, 'corriente': 2.3149326279699625, 'temperatura': 22.742054728169663, 'potencia': 55.558383071279096, 'estado_temperatura': 'Normal'}, {'id': 50, 'voltaje': 24.0, 'corriente': 2.381132213792293, 'temperatura': 24.46662209955532, 'potencia': 57.14717313101502, 'estado_temperatura': 'Normal'}, {'id': 51, 'voltaje': 24.0, 'corriente': 2.210786421564651, 'temperatura': 23.95247428541376, 'potencia': 53.058874117551625, 'estado_temperatura': 'Normal'}, {'id': 52, 'voltaje': 24.0, 'corriente': 2.2302343257074138, 'temperatura': 23.770483535971927, 'potencia': 53.52562381697793, 'estado_temperatura': 'Normal'}, {'id': 53, 'voltaje': 24.0, 'corriente': 2.263890993700954, 'temperatura': 24.851118442797624, 'potencia': 54.33338384882289, 'estado_temperatura': 'Normal'}, {'id': 54, 'voltaje': 24.0, 'corriente': 2.157567196916137, 'temperatura': 25.234588652421497, 'potencia': 51.78161272598729, 'estado_temperatura': 'Normal'}, {'id': 55, 'voltaje': 24.0, 'corriente': 2.2077946101551005, 'temperatura': 25.201060895600133, 'potencia': 52.98707064372241, 'estado_temperatura': 'Normal'}, {'id': 56, 'voltaje': 24.0, 'corriente': 2.239342533890844, 'temperatura': 23.829128192304413, 'potencia': 53.74422081338026, 'estado_temperatura': 'Normal'}, {'id': 57, 'voltaje': 24.0, 'corriente': 2.371328944377497, 'temperatura': 24.29579757989844, 'potencia': 56.91189466505993, 'estado_temperatura': 'Normal'}, {'id': 58, 'voltaje': 24.0, 'corriente': 2.30675616011048, 'temperatura': 24.849026288981683, 'potencia': 55.362147842651524, 'estado_temperatura': 'Normal'}, {'id': 59, 'voltaje': 24.0, 'corriente': 2.296157381411163, 'temperatura': 25.40346616373799, 'potencia': 55.107777153867914, 'estado_temperatura': 'Normal'}, {'id': 60, 'voltaje': 24.0, 'corriente': 2.357879024264502, 'temperatura': 24.2768560395599, 'potencia': 56.58909658234805, 'estado_temperatura': 'Normal'}, {'id': 61, 'voltaje': 24.0, 'corriente': 2.2547398159024814, 'temperatura': 24.546969600264283, 'potencia': 54.113755581659554, 'estado_temperatura': 'Normal'}, {'id': 62, 'voltaje': 24.0, 'corriente': 2.3029129662781576, 'temperatura': 23.84385201804287, 'potencia': 55.269911190675785, 'estado_temperatura': 'Normal'}, {'id': 63, 'voltaje': 24.0, 'corriente': 2.2486406347014123, 'temperatura': 23.803486408688045, 'potencia': 53.967375232833895, 'estado_temperatura': 'Normal'}, {'id': 64, 'voltaje': 24.0, 'corriente': 2.2803076638297464, 'temperatura': 25.440099959361486, 'potencia': 54.72738393191391, 'estado_temperatura': 'Normal'}, {'id': 65, 'voltaje': 24.0, 'corriente': 2.1900222398766296, 'temperatura': 25.902782949942623, 'potencia': 52.56053375703911, 'estado_temperatura': 'Normal'}, {'id': 66, 'voltaje': 24.0, 'corriente': 1.9986672053182344, 'temperatura': 24.78596740332706, 'potencia': 47.96801292763762, 'estado_temperatura': 'Normal'}, {'id': 67, 'voltaje': 24.0, 'corriente': 2.223102346586731, 'temperatura': 25.670249026790216, 'potencia': 53.35445631808154, 'estado_temperatura': 'Normal'}, {'id': 68, 'voltaje': 24.0, 'corriente': 2.3725236310052105, 'temperatura': 25.17863183221469, 'potencia': 56.940567144125055, 'estado_temperatura': 'Normal'}, {'id': 69, 'voltaje': 24.0, 'corriente': 2.3163331038771755, 'temperatura': 24.3931718481777, 'potencia': 55.59199449305221, 'estado_temperatura': 'Normal'}, {'id': 70, 'voltaje': 24.0, 'corriente': 2.3134655129806148, 'temperatura': 25.21636513434903, 'potencia': 55.52317231153475, 'estado_temperatura': 'Normal'}, {'id': 71, 'voltaje': 24.0, 'corriente': 2.333512031259993, 'temperatura': 26.17368806743137, 'potencia': 56.00428875023984, 'estado_temperatura': 'Normal'}, {'id': 72, 'voltaje': 24.0, 'corriente': 2.211504713261489, 'temperatura': 24.92863090967047, 'potencia': 53.07611311827574, 'estado_temperatura': 'Normal'}, {'id': 73, 'voltaje': 24.0, 'corriente': 2.2148853864452183, 'temperatura': 26.221056741709425, 'potencia': 53.15724927468524, 'estado_temperatura': 'Normal'}, {'id': 74, 'voltaje': 24.0, 'corriente': 2.1256866702043418, 'temperatura': 22.883608139416403, 'potencia': 51.0164800849042, 'estado_temperatura': 'Normal'}, {'id': 75, 'voltaje': 24.0, 'corriente': 2.147934357628482, 'temperatura': 25.644996936520453, 'potencia': 51.55042458308357, 'estado_temperatura': 'Normal'}, {'id': 76, 'voltaje': 24.0, 'corriente': 2.2330090694476885, 'temperatura': 25.063188374468453, 'potencia': 53.592217666744524, 'estado_temperatura': 'Normal'}, {'id': 77, 'voltaje': 24.0, 'corriente': 2.2835202471138105, 'temperatura': 24.758423272654703, 'potencia': 54.80448593073145, 'estado_temperatura': 'Normal'}, {'id': 78, 'voltaje': 24.0, 'corriente': 2.140705783978339, 'temperatura': 25.07311722237824, 'potencia': 51.376938815480145, 'estado_temperatura': 'Normal'}, {'id': 79, 'voltaje': 24.0, 'corriente': 2.100978275330148, 'temperatura': 23.409733100812986, 'potencia': 50.423478607923556, 'estado_temperatura': 'Normal'}, {'id': 80, 'voltaje': 24.0, 'corriente': 2.1372345838764035, 'temperatura': 24.822130504937515, 'potencia': 51.293630013033685, 'estado_temperatura': 'Normal'}, {'id': 81, 'voltaje': 24.0, 'corriente': 2.18833463896306, 'temperatura': 25.279638774562017, 'potencia': 52.520031335113444, 'estado_temperatura': 'Normal'}, {'id': 82, 'voltaje': 24.0, 'corriente': 1.9747182117663709, 'temperatura': 26.17034714238908, 'potencia': 47.3932370823929, 'estado_temperatura': 'Normal'}, {'id': 83, 'voltaje': 24.0, 'corriente': 1.8802430021915009, 'temperatura': 24.56550377496377, 'potencia': 45.125832052596024, 'estado_temperatura': 'Normal'}, {'id': 84, 'voltaje': 24.0, 'corriente': 2.0454427600976133, 'temperatura': 24.323421128675825, 'potencia': 49.09062624234272, 'estado_temperatura': 'Normal'}, {'id': 85, 'voltaje': 24.0, 'corriente': 1.968948897618941, 'temperatura': 24.556918417394712, 'potencia': 47.254773542854586, 'estado_temperatura': 'Normal'}, {'id': 86, 'voltaje': 24.0, 'corriente': 2.0306286914839538, 'temperatura': 25.67677052418517, 'potencia': 48.73508859561489, 'estado_temperatura': 'Normal'}, {'id': 87, 'voltaje': 24.0, 'corriente': 2.056996766882448, 'temperatura': 25.19159678190552, 'potencia': 49.36792240517875, 'estado_temperatura': 'Normal'}, {'id': 88, 'voltaje': 24.0, 'corriente': 2.016702302984964, 'temperatura': 24.48696342267446, 'potencia': 48.40085527163913, 'estado_temperatura': 'Normal'}, {'id': 89, 'voltaje': 24.0, 'corriente': 2.1974573297898035, 'temperatura': 25.30159698053091, 'potencia': 52.73897591495528, 'estado_temperatura': 'Normal'}, {'id': 90, 'voltaje': 24.0, 'corriente': 2.075010478878192, 'temperatura': 24.94690019386941, 'potencia': 49.80025149307661, 'estado_temperatura': 'Normal'}, {'id': 91, 'voltaje': 24.0, 'corriente': 2.0624618288069825, 'temperatura': 25.620461636828598, 'potencia': 49.499083891367576, 'estado_temperatura': 'Normal'}, {'id': 92, 'voltaje': 24.0, 'corriente': 2.0846774850208183, 'temperatura': 24.25827250566036, 'potencia': 50.03225964049964, 'estado_temperatura': 'Normal'}, {'id': 93, 'voltaje': 24.0, 'corriente': 1.8985908869519104, 'temperatura': 24.53022669811636, 'potencia': 45.56618128684585, 'estado_temperatura': 'Normal'}, {'id': 94, 'voltaje': 24.0, 'corriente': 2.106388946648018, 'temperatura': 24.44919444885225, 'potencia': 50.55333471955244, 'estado_temperatura': 'Normal'}, {'id': 95, 'voltaje': 24.0, 'corriente': 1.9849021556079032, 'temperatura': 23.56068847993138, 'potencia': 47.637651734589674, 'estado_temperatura': 'Normal'}, {'id': 96, 'voltaje': 24.0, 'corriente': 2.0495358186958472, 'temperatura': 24.935123590078287, 'potencia': 49.18885964870033, 'estado_temperatura': 'Normal'}, {'id': 97, 'voltaje': 24.0, 'corriente': 1.865330662624192, 'temperatura': 24.871919287854915, 'potencia': 44.767935902980604, 'estado_temperatura': 'Normal'}, {'id': 98, 'voltaje': 24.0, 'corriente': 1.807199672804624, 'temperatura': 24.63014836925481, 'potencia': 43.372792147310975, 'estado_temperatura': 'Normal'}, {'id': 99, 'voltaje': 24.0, 'corriente': 2.0344652575595283, 'temperatura': 24.39952006970893, 'potencia': 48.82716618142868, 'estado_temperatura': 'Normal'}, {'id': 100, 'voltaje': 24.0, 'corriente': 1.980470563747106, 'temperatura': 23.41419054048808, 'potencia': 47.531293529930544, 'estado_temperatura': 'Normal'}, {'id': 101, 'voltaje': 24.0, 'corriente': 1.8428412918547148, 'temperatura': 24.167449699400848, 'potencia': 44.22819100451316, 'estado_temperatura': 'Normal'}, {'id': 102, 'voltaje': 24.0, 'corriente': 1.8363713612644808, 'temperatura': 24.185471641545483, 'potencia': 44.072912670347534, 'estado_temperatura': 'Normal'}, {'id': 103, 'voltaje': 24.0, 'corriente': 2.026257542415476, 'temperatura': 23.771714938702576, 'potencia': 48.630181017971424, 'estado_temperatura': 'Normal'}, {'id': 104, 'voltaje': 24.0, 'corriente': 1.78524513365474, 'temperatura': 24.236636328204774, 'potencia': 42.845883207713754, 'estado_temperatura': 'Normal'}, {'id': 105, 'voltaje': 24.0, 'corriente': 2.05903232701871, 'temperatura': 24.639287518696, 'potencia': 49.41677584844904, 'estado_temperatura': 'Normal'}, {'id': 106, 'voltaje': 24.0, 'corriente': 1.7953985838962898, 'temperatura': 25.773651128732805, 'potencia': 43.089566013510954, 'estado_temperatura': 'Normal'}, {'id': 107, 'voltaje': 24.0, 'corriente': 1.9401227297426964, 'temperatura': 24.351314408448697, 'potencia': 46.562945513824715, 'estado_temperatura': 'Normal'}, {'id': 108, 'voltaje': 24.0, 'corriente': 1.8343820194366456, 'temperatura': 24.362957616471625, 'potencia': 44.02516846647949, 'estado_temperatura': 'Normal'}, {'id': 109, 'voltaje': 24.0, 'corriente': 1.918670433106364, 'temperatura': 24.04096300549394, 'potencia': 46.04809039455274, 'estado_temperatura': 'Normal'}, {'id': 110, 'voltaje': 24.0, 'corriente': 1.7952054852120771, 'temperatura': 22.50746504685872, 'potencia': 43.08493164508985, 'estado_temperatura': 'Normal'}, {'id': 111, 'voltaje': 24.0, 'corriente': 1.8247698671202224, 'temperatura': 23.96161626082106, 'potencia': 43.794476810885335, 'estado_temperatura': 'Normal'}, {'id': 112, 'voltaje': 24.0, 'corriente': 1.836749943265588, 'temperatura': 23.969763793374923, 'potencia': 44.08199863837412, 'estado_temperatura': 'Normal'}, {'id': 113, 'voltaje': 24.0, 'corriente': 1.7242340664577875, 'temperatura': 25.82935700008886, 'potencia': 41.3816175949869, 'estado_temperatura': 'Normal'}, {'id': 114, 'voltaje': 24.0, 'corriente': 1.890525067259197, 'temperatura': 23.64051476907971, 'potencia': 45.37260161422073, 'estado_temperatura': 'Normal'}, {'id': 115, 'voltaje': 24.0, 'corriente': 1.757315030497786, 'temperatura': 23.96976393475049, 'potencia': 42.17556073194687, 'estado_temperatura': 'Normal'}, {'id': 116, 'voltaje': 24.0, 'corriente': 1.7781827565883233, 'temperatura': 23.633387804387063, 'potencia': 42.676386158119755, 'estado_temperatura': 'Normal'}, {'id': 117, 'voltaje': 24.0, 'corriente': 1.6942352147839568, 'temperatura': 22.657381535250007, 'potencia': 40.66164515481496, 'estado_temperatura': 'Normal'}, {'id': 118, 'voltaje': 24.0, 'corriente': 1.53029342464759, 'temperatura': 24.436312080462898, 'potencia': 36.72704219154216, 'estado_temperatura': 'Normal'}, {'id': 119, 'voltaje': 24.0, 'corriente': 1.760517823042936, 'temperatura': 24.0519213439341, 'potencia': 42.25242775303046, 'estado_temperatura': 'Normal'}, {'id': 120, 'voltaje': 24.0, 'corriente': 2.014220793568913, 'temperatura': 24.01014146039019, 'potencia': 48.34129904565391, 'estado_temperatura': 'Normal'}, {'id': 121, 'voltaje': 24.0, 'corriente': 1.845010576443292, 'temperatura': 22.57539604256021, 'potencia': 44.28025383463901, 'estado_temperatura': 'Normal'}, {'id': 122, 'voltaje': 24.0, 'corriente': 1.7584743706341623, 'temperatura': 24.34941044042073, 'potencia': 42.2033848952199, 'estado_temperatura': 'Normal'}, {'id': 123, 'voltaje': 24.0, 'corriente': 1.7282277837598503, 'temperatura': 22.02867229974564, 'potencia': 41.47746681023641, 'estado_temperatura': 'Normal'}, {'id': 124, 'voltaje': 24.0, 'corriente': 1.751152647817447, 'temperatura': 23.54135696406877, 'potencia': 42.02766354761873, 'estado_temperatura': 'Normal'}, {'id': 125, 'voltaje': 24.0, 'corriente': 1.798286129345869, 'temperatura': 24.74472522116777, 'poten

## Parte 5 — Comprensión de listas

Use comprensión de listas para obtener:

1. Lista de potencias válidas.
2. Lista de temperaturas válidas.
3. Lista de motores en alerta.

In [10]:
# TODO: use comprensión de listas
#Lista de potencias válidas (excluye los valores None)
potencias_validas = [
    reg["potencia"]
    for reg in registros_limpios
    if reg["potencia"] is not None]

# Lista de temperaturas válidas (excluye los valores None)
temperaturas_validas = [
    reg["temperatura"]
    for reg in registros_limpios
    if reg["temperatura"] is not None
]

#Lista de IDs de motores en alerta (donde el estado_temperatura sea "Alerta")
motores_en_alerta = [
    reg["id"]
    for reg in registros_limpios
    if reg["estado_temperatura"] == "Alerta"
]

print("Potencias válidas:", potencias_validas)
print("Temperaturas válidas:", temperaturas_validas)
print("Motores en alerta (IDs):", motores_en_alerta)

Potencias válidas: [46.37957214006148, 47.893110748307386, 46.57783671304852, 47.979692928723466, 44.41248288219157, 49.70635705308764, 49.433312322593785, 47.703784286003284, 51.47951482047122, 52.377913818265384, 46.49765814244675, 48.75070136212714, 48.95787042513277, 48.767500797606125, 53.2301051606394, 50.98668114489553, 51.0256915475599, 47.05585390506031, 53.59042908094639, 49.286991168054676, 52.596100894741284, 53.30407199921103, 56.08489947981612, 49.8537470906838, 45.91813468050658, 53.77051225042034, 57.8088888006057, 56.61342499637252, 54.28916209525886, 52.74565013149851, 55.9956853225464, 51.848363180337856, 55.4475442290871, 55.62982137444223, 57.066475181498454, 61.24318794401363, 55.65247974019307, 53.57239066328904, 54.808198879167975, 50.691836763269905, 53.33064137520211, 54.0682342098729, 53.83742590087389, 55.49773287546624, 53.18719267061513, 57.87243750512792, 55.19544503353463, 55.17761783462059, 54.40998262226784, 55.558383071279096, 57.14717313101502, 53.058874117551625, 53.52562381697793, 54.33338384882289, 51.78161272598729, 52.98707064372241, 53.74422081338026, 56.91189466505993, 55.362147842651524, 55.107777153867914, 56.58909658234805, 54.113755581659554, 55.269911190675785, 53.967375232833895, 54.72738393191391, 52.56053375703911, 47.96801292763762, 53.35445631808154, 56.940567144125055, 55.59199449305221, 55.52317231153475, 56.00428875023984, 53.07611311827574, 53.15724927468524, 51.0164800849042, 51.55042458308357, 53.592217666744524, 54.80448593073145, 51.376938815480145, 50.423478607923556, 51.293630013033685, 52.520031335113444, 47.3932370823929, 45.125832052596024, 49.09062624234272, 47.254773542854586, 48.73508859561489, 49.36792240517875, 48.40085527163913, 52.73897591495528, 49.80025149307661, 49.499083891367576, 50.03225964049964, 45.56618128684585, 50.55333471955244, 47.637651734589674, 49.18885964870033, 44.767935902980604, 43.372792147310975, 48.82716618142868, 47.531293529930544, 44.22819100451316, 44.072912670347534, 48.630181017971424, 42.845883207713754, 49.41677584844904, 43.089566013510954, 46.562945513824715, 44.02516846647949, 46.04809039455274, 43.08493164508985, 43.794476810885335, 44.08199863837412, 41.3816175949869, 45.37260161422073, 42.17556073194687, 42.676386158119755, 40.66164515481496, 36.72704219154216, 42.25242775303046, 48.34129904565391, 44.28025383463901, 42.2033848952199, 41.47746681023641, 42.02766354761873, 43.15886710430085, 38.890703681880936, 44.28487167716081, 43.220358725894016, 43.12725099710296, 42.36343736399386, 41.273097332639445, 42.76333203431585, 42.49887881452321, 40.16657682867039, 39.58513889785874, 41.15956639619428, 44.593959155606534, 37.8715677922697, 37.30042690984308, 41.20295061586256, 40.92268302999292, 41.21759913407506, 41.396090913463695, 40.291929405258415, 44.4282672259239, 37.04334640767052, 38.93794832963221, 40.72721389102301, 37.087861099606755, 40.67369465178843, 45.15517528013062, 41.29726691482474, 41.88781646096517, 38.4041396268474, 40.050969411644, 40.738655166037454, 40.992566917335225, 44.95392308233766, 43.346132961728216, 39.47652928406455, 42.87849984636438, 43.631827885989175, 45.32784223702075, 46.54617995251276, 40.48388359550629, 41.14692278013434, 40.25311683551911, 42.893232545462524, 44.76276648191098, 46.20657549925481, 43.85278163655495, 43.46992654778209, 44.80845639643772, 42.65052134430889, 49.8841008067669, 41.22864331192557, 45.75146540257204, 50.38879191197003, 45.77524740148928, 45.532114728964146, 45.36185515366397, 46.020277788728635, 49.983266308464586, 41.61663069143658, 50.84320369467754, 43.984259133833675, 47.00124885137622, 46.85088458835661, 49.533587930937045, 44.52541602663065, 49.70958227846332, 53.697497370812, 45.805390751648446, 49.76896068752448, 47.960106687520415, 50.80447043750584, 50.05979284116489, 48.70352923558998, 51.640758842770865, 55.02432432360097, 50.45675032829398, 52.86013055843465, 48.24316799895869, 49.26216882383475, 52.898031684646604, 55.52859345565754, 53.018238340680625, 51.60685125710621, 52.545072144578846, 49.72932494924796, 54.35941562708961, 55.19900005496034, 52.1635602901069, 52.28182110544172, 54.203364714210004, 52.66628125321648, 53.6984932462503, 59.03283930676025, 53.530281986735275, 53.385961096404486, 52.80777158807028, 56.25675902144357, 54.13739764328786, 53.10817581717198, 57.92472951023335, 58.240072462220425, 53.463842564905164, 50.48932575536122, 57.44347436975868, 53.43094448447788, 57.01231272190505, 50.419412725096855, 57.3148049920016, 52.28269945642327, 56.95229907194204, 55.23367609437916, 52.90292305469441, 54.20045664909115, 56.8015001476185, 55.37752606316491, 56.487099920446084, 59.78122461419685, 51.2290267699781, 58.80219784465778, 55.101333778253306, 52.616178292118875, 51.495362638575756, 54.141651183524566, 56.707597471664016, 54.08239968937571, 57.901072090477726, 50.67029048211188, 53.9960743855047, 50.884625393618364, 54.62182372918905, 55.729987192350976, 52.43775613115361, 47.0375458487885, 53.59933469290538, 53.998541272974464, 53.743685868499796, 55.55696216197203, 49.83316178231841, 53.84392244190175, 54.87645608982518, 47.54440205557932, 52.37451454870231, 50.18764868564133, 50.988581127410214, 51.80167665423265, 49.57762544813431, 48.90194360954963, 50.3794740108866, 47.45943061448405, 47.23185474025048, 51.2353032606174, 46.61289107487259, 50.732814061486586, 50.00629095210033, 44.51554794689676, 46.792010706887424, 51.044245630577876, 45.58360479424799, 46.58391928096829, 48.567858076479524, 49.10007273041561, 46.37813241516672, 45.3108227079346, 49.92295076191562, 50.44869442657591, 48.39258281171752, 46.018249172091345, 43.64623927356058, 43.368283693650355, 46.393588947489285, 45.92509362829295, 48.06957818788912, 46.05528540180927, 40.67917103731681, 46.60772228413154, 41.488538502021555, 42.767761999630864, 44.09997182297532, 48.104291681300495, 50.5988980363965, 44.41703759125333, 42.35263759083468, 43.91231604560796, 44.603035191799414, 41.55236046665553, 46.48607896659216, 42.591819244642664, 43.10293254515396, 43.38203491929199, 42.67799839367867, 43.56905845765116, 39.97076411720047, 40.016092754917324, 38.6268735245913, 42.24075350425417, 42.98167549128372, 42.144812465246076, 45.00659490632372, 40.92382869833155, 42.49953195742293, 38.2396569330001, 39.903819690255524, 42.483232287505146, 42.840853198261286, 40.0945498384409, 40.63329386967912, 37.175290200918155, 39.98235128299542, 43.00513081338524, 42.28561659165855, 42.15151808142542, 41.12200569299577, 41.079903143973496, 39.546290665968684, 42.88399089397459, 42.300426334959994, 42.561679850397056, 40.216448286847466, 36.416251155939015, 44.32991085045218, 40.66700759537489, 39.87189903693106, 43.73998350481889, 41.274459045289795, 44.90521882880844, 43.99453247476704, 44.31272656441049, 39.5582277486956, 45.91528495453208, 43.80926628556877, 42.47699804066312, 43.89354511351476, 39.47754248901226, 44.917100383340184, 41.666183370759896, 41.09489984487999, 40.896344860837914, 47.43299035532669, 43.468434304734615, 48.87909787409628, 44.13482565656932, 41.5485534361826, 43.19463232229573, 49.070678990182884, 45.96312125846359, 45.255780456351, 47.191693678818865, 48.249233183156385, 49.965077517387606, 50.99888049081438, 46.89873009508051, 44.81961712998592, 47.24976955329632, 49.10644455972775, 46.407900073029865, 46.662108502475476, 50.021645058586955, 49.31574256223634, 49.74558352971889, 48.078992565058165, 49.57682005351151, 48.13965641554746, 52.719706789728484, 53.29037365713265, 46.59435179578039, 49.01044298697492, 47.862064148899776, 50.10230510090453, 51.66667068340668, 48.58803636907636, 50.050465754391254, 50.04443987287465, 53.1374390550954, 52.98732869670255, 51.26428092094541, 53.59081880497114, 52.01867420464819, 52.83706937998281, 57.657563528123966, 57.00435439546851, 50.80779258227105, 56.05110032376114, 56.13331679774659, 51.54948306194987, 56.382725931122636, 58.213910748811045, 51.926734201258554, 52.509446747748406, 57.23699634042195, 55.52180400144643, 56.26173188578704, 55.81586812940502, 55.98861406507075, 51.912066935013925, 57.64593545689455, 57.968237735782765, 54.63157658480985, 55.090682919431735, 51.52528908635493, 56.431078799929125, 56.55872975967175, 55.01747449886083, 57.838159744141024, 54.302972788425365, 56.41696538244818, 52.564023923520054, 54.89621082905662, 54.46807888002482, 55.35341022919225, 53.84437977057765, 54.32680488569445, 56.52856734884294, 53.39426227003991, 50.47599603307373, 58.41303241946275, 57.4048669730863, 50.85652750264182, 55.47521814978488, 52.46827543577906, 54.156974237132474, 54.073794983648426, 52.64216699572707, 51.15501424620079, 51.20446435010462, 50.48321185197626, 50.50080690180137, 52.146063653624296, 50.394793487686115, 53.55029917920723, 55.279173963264334, 50.10994278045925, 51.865037901092656, 52.27445216855273, 51.989337576746664, 50.81697536153972, 52.19234396041018, 51.33984965500263, 46.982183644875605, 51.80649997769709, 51.61606387939232, 47.419068079790556, 49.10500457375491, 50.415815879302556, 48.03448370803704, 50.87239833794882, 53.73062891034521, 45.93098864531128, 44.26307119640427, 48.067435307812396, 48.83144831177599, 46.30804686596097, 50.113643806076325, 43.17838307296696, 47.821048036925724, 44.4730301501902, 49.824958886550206, 50.254401589775085, 43.409109985595094, 43.70992601253019, 46.87495236741595, 43.66944813843621, 44.2799740601222, 44.24430437177186, 39.37480807186082, 43.751928545187695, 41.93759071226488, 42.22213711333532, 46.688147593300464, 40.030919944315066, 44.826837983137466, 42.03993730201309, 41.87820457675037, 44.29275758507716, 43.06445043502361, 43.476650970589674, 44.29622238353669, 41.04953501375497, 40.25424152232483, 39.00515609447445, 39.521539638169365, 48.48057783109225, 44.297538102080836, 37.9827168312619, 37.973911168520274, 42.234416606591566, 42.32919183375178, 42.278655338622336, 40.30283805888329, 40.57491136008733, 41.63209688365981, 41.0284627396045, 35.48110659084077, 40.24900734027795, 38.75824865404957, 41.23122659917301, 47.99242324773316, 41.73480845774978, 40.13337257269191, 43.13906266924165, 42.13394368993137, 42.04027751923129, 42.55279159638347, 46.1040241705804, 38.533746865692535, 42.47165725221448, 39.20609164954778, 42.86440278999774, 39.43527780916911, 40.75446395505161, 41.17088435958859, 44.350816496372914, 44.34955946149907, 39.29846417323465, 42.569290696297834, 40.889900171845916, 39.73393037267679, 42.400779541389014, 42.35418219570643, 49.097030886288806, 44.49563716543302, 40.33892167686459, 42.48325437734346, 46.48816343031041, 49.25164080957535, 40.63973092056018, 40.144933483148684, 49.36144394197461, 46.02405326346053, 43.22616256599202, 46.81724935371264, 39.43515898916959, 45.99835639346317, 47.00856045031974, 48.673548034610654, 44.2571756531944, 47.132856201505824, 44.94406086887702, 48.016801545347306, 45.4945122120045, 46.90376047407332, 45.733234405940934, 49.92577033258581, 50.66277468680291, 48.278181919966315, 49.17088709747732, 45.839142229500645, 48.83172156245344, 49.66391521657711, 56.30578800566704, 47.57640235067923, 53.9858928605091, 53.088326553654625, 51.59039574918041, 55.355319756753154, 52.24196334481997, 52.493451229225464, 51.6385839418933, 54.90505903777363, 54.798031062748024, 50.85826157199022, 49.38223208489699, 52.244756774118414, 50.99004550993622, 52.930451642215274, 56.219887545781354, 52.31380461832716, 53.46383301276137, 53.85495968024493, 55.89468502734384, 48.60215351463338, 52.66818406726826, 54.75411838609074, 57.243059259829906, 53.291066929474184, 50.069479310738416, 56.15478339153236, 53.229468683356615, 51.97849680444797, 53.40703392727983, 54.5266960544425, 53.574520533030515, 49.78109416465125, 57.26809677278045, 58.20761822108747, 56.73640972710915, 52.45918117271911, 54.71492919955317, 55.18374222112382, 56.62938582394612, 56.781191691730754, 53.39207873155964, 55.319858254444725, 56.181601172330616, 58.531290531843965, 56.673502894620526, 56.81403566611648, 55.05140743096236, 58.1576387251953, 55.67075639565893, 52.528073935687175, 57.86280533390321, 56.0625020606786, 53.20994875375858, 53.001221843291795, 54.735701905797434, 55.000787113125114, 54.22132516198377, 54.34725878123079, 57.52608812727827, 55.85791569457453, 53.577886223959126, 55.20796611146061, 50.29372508128099, 53.54446761215405, 56.744339265554025, 51.68636454844534, 49.97834695664136, 50.24619063302646, 48.99038597736243, 49.51237224277173, 50.29310417828072, 47.59194997374642, 50.782487541394616, 52.687111755608036, 48.116873134703766, 53.71306050629991, 51.061675015942214, 52.07612276285598, 47.789101136482024, 51.18241956637526, 46.2733154447645, 50.79195539864652, 48.82845229116093, 49.50405506113191, 45.11484351960945, 45.54819219550397, 48.890134131378275, 44.94178130280854, 48.09141073165584, 43.46161755712032, 48.542795882031356, 43.315209832981324, 47.36679207157848, 47.312969057310866, 43.91181653946221, 46.75623087117063, 45.762660513526214, 43.625790749011685, 42.283315088362095, 39.78204185027014, 45.12389783918597, 40.325732976759404, 44.11096136187028, 43.0553102014045, 45.12777034539674, 42.58816220042735, 42.342847643096825, 44.71586964851146, 43.59497702628331, 43.38685727412817, 43.59753865688448, 38.635279245279946, 43.992610874593154, 43.50837900851282, 39.467173581355176, 41.19694827660598, 41.57083967208728, 41.231858669134134, 42.252549496632845, 44.7904761540812, 43.862728757014104, 38.035936265876025, 42.604575256023594, 44.235045256385284, 41.915670139153285, 43.555198244403556, 45.72365705121316, 43.316368243205666, 41.430996505919204, 43.32202173635176, 41.15067763708137, 40.85744756595902, 39.96181869090332, 44.57053098011457, 38.8752150675547, 44.546186788767955, 42.10516168074372, 37.592018559958824, 41.885409493823595, 36.02345905118289, 42.632919872274805, 43.33206489054078, 39.86921025035317, 41.67818813149888, 46.169813634552995, 40.37144979179261, 39.15639661064422, 45.373301747118745, 46.65392262007603, 42.08571534115356, 44.644070052783576, 45.582239454993804, 40.73313667930941, 41.50886018255628, 45.79210604976491, 47.05218953433419, 44.53476335769667, 41.253339655810386, 48.320035224047956, 42.467895630222394, 43.133762761373966, 44.960084701814075, 48.07312955890298, 46.601420339578745, 45.760119535327235, 46.09249387655619, 45.304550255533535, 46.76227422738365, 39.577282905579665, 45.164469728851095, 46.68596023048076, 43.576917116635926, 47.50093520551786, 46.31902120307608, 51.260209075253215, 51.060688721631024, 46.406675877560524, 47.402294761057846, 47.82678899551866, 47.16023355795856, 48.951958083850926, 46.9031653634967, 46.24790642563928, 50.69316296282819, 50.94546810686373, 47.73858651161507, 52.05029038779842, 48.61603131058335, 50.9674264712862, 52.55404577922951, 50.727068041762394, 52.118515014025114, 50.00374113345264, 50.9840847413449, 51.17013496514903, 50.076931671550014, 51.64468563630713, 48.54796300517518, 51.27684316612323, 51.95792599019555, 52.20765389730134, 52.418391741326275, 53.01969903670874, 54.482798648490075, 55.58926182137119, 52.083166234620265, 50.900833683574895, 51.42709101593074, 52.89160640909949, 53.342444369364266, 52.458353215764504, 51.307945623091484, 53.42908632809251, 55.05710292984008, 56.14029574716804, 53.45749835202123, 53.87965790720316, 52.71468216607582, 54.92350050797906, 53.01514630829024, 56.47146815987517, 50.84658453364809, 54.29833115803452, 55.904921822166685, 55.636309328790716, 61.66323574212374, 56.03632425725319, 52.77592670686436, 54.93741376234944, 50.8764448995523, 54.91097287377316, 53.06216084696327, 57.207669777271626, 53.633285206840085, 54.60566848660383, 53.28664238475805, 58.90373080098337, 53.87053364316323, 58.943303132230035, 56.395508669423705, 55.48772618949015, 55.097913667788646, 55.033353057107, 49.33034669385725, 53.14934407083168, 55.70248209628536, 53.40588449863797, 49.99378051757226, 53.07750194689042, 57.12438146692989, 55.852730542523545, 52.531643288502735, 54.778993639937426, 51.425966435532644, 48.021575846967465, 49.69286644696125, 55.45888922307009, 50.842624572591575, 50.70444944893814, 50.35366872937546, 55.42450317657626, 54.53500026290382, 55.732969980625704, 49.798712275844125, 50.66002044880969, 46.07851340657623, 53.02912277900077, 46.44618459472737, 49.53210474349061, 46.14018103049274, 47.12143082403453, 46.28569141652865, 46.59630278612651, 46.52132975344642, 46.25960524982905, 49.33614954071571, 44.44591278875566, 47.3893208487727, 49.54682784689139, 45.15728811582291, 44.43297744154055, 45.37179578589823, 48.52777277449949, 45.93622725953608, 43.97220174993549, 46.188225608319414, 42.164529188868045, 46.23194595909581, 45.36777457113611, 43.44282454326385, 41.96764911193611, 41.65537693870476, 44.87481354832124, 46.35354409136707, 41.69229744079753, 44.14511784997477, 37.86478370176671, 41.30492019647152, 42.47369496731617, 40.2112868158514, 39.99943005415575, 40.50328433515185, 42.672676067914274, 41.39397993422979, 36.350810521791345, 36.518855300253094, 40.04513039402945, 42.50034555005607, 34.71550758956531, 40.02522143716682, 39.884161206346036, 44.4093624977885, 40.09118636919739, 41.88005929520598, 41.253370396470984, 35.762333449030066, 42.688645224529566, 41.339103743549096, 42.02717573960098, 50.22347148823757, 35.799798629081764, 44.9501077386472, 40.138115048648594, 41.54269994493703, 40.77694291780841, 39.908970359682264, 39.60836179378154, 41.82340881401182, 37.45573885597828, 42.970382948423946, 40.24975289811337, 38.62358041896905, 40.35024737644801, 44.54926677405722, 40.35632074324136, 42.61749469681555, 40.125927807951705, 43.82905128882557, 43.79172829760707, 46.72614507581895, 42.01744898854216, 44.19907110725376, 42.991164566505994, 46.03322399049763, 41.370903668649305, 45.06253210642538, 42.99091384935641, 43.49284973073405, 44.060657642666825, 44.644000248045366, 43.96224633189575, 44.96325647592046, 48.44612333791862, 47.23812668717796, 47.176899975666494, 44.21874760507567, 43.40196433659591, 48.055700887091135, 48.094814420511796, 49.75826488024076, 45.00782820754346, 46.14170525005866, 42.99455285361415, 46.2252665499058, 49.797774041382624, 46.52588345092488, 49.422485297761256, 47.66811515819556, 49.14290906917854, 45.85015674542297, 49.047890906191185, 41.90249703173235, 48.869306469071475, 45.639891200255164, 52.68085813562662, 51.88370846897177, 51.36715876771845, 54.124284344457024, 48.420442248296524, 55.112488747711325, 53.373809171574685, 50.783064340430215, 54.28681023230928, 49.112785640664285, 49.99143811727376, 50.707627798651984, 51.09203671211598, 50.01433919102496, 55.66891604325188, 52.290446293898086, 53.930432015754924, 51.88265121662995, 49.04328652540343, 54.2160984650162, 49.127589171724, 53.69496807466945, 50.711912201017256, 58.894847742264965, 56.43536757367005, 54.61767614858154, 57.50546277628666, 52.542917029427215, 55.97263065770803, 55.23462144922575, 55.46801591738997, 57.959714397518425, 56.72807262281738, 55.71931011667492, 51.1031188700739, 52.811352784297256, 54.853672289308705, 55.39703558529898, 52.47725190741378, 60.98657596633278, 58.8387111253809, 56.637264255309205, 55.349893075522694, 54.644553691536096, 52.83815353404725, 55.26970025873887, 55.655472185566865, 52.0019417668305, 55.72173436294187, 54.47694520208544]

## Parte 6 — Comprensión de diccionarios

Cree un diccionario llamado `estado_por_motor` donde:

- La clave sea el `id` del motor.
- El valor sea el `estado_temperatura`.

In [11]:
# TODO: cree el diccionario estado_por_motor
estado_por_motor = {
    reg["id"]: reg["estado_temperatura"] for reg in registros_limpios}
print(estado_por_motor)

{0: 'Normal', 1: 'Normal', 2: 'Normal', 3: 'Normal', 4: 'Normal', 5: 'Normal', 6: 'Normal', 7: 'Normal', 8: 'Normal', 9: 'Normal', 10: 'Normal', 11: 'Normal', 12: 'Normal', 13: 'Normal', 14: 'Normal', 15: 'Normal', 16: 'Normal', 17: 'Normal', 18: 'Normal', 19: 'Normal', 20: 'Normal', 21: 'Normal', 22: 'Normal', 23: 'Normal', 24: 'Normal', 25: 'Normal', 26: 'Normal', 27: 'Normal', 28: 'Normal', 29: 'Normal', 30: 'Normal', 31: 'Normal', 32: 'Normal', 33: 'Normal', 34: 'Normal', 35: 'Normal', 36: 'Normal', 37: 'Normal', 38: 'Normal', 39: 'Normal', 40: 'Normal', 41: 'Normal', 42: 'Normal', 43: 'Normal', 44: 'Normal', 45: 'Normal', 46: 'Normal', 47: 'Normal', 48: 'Normal', 49: 'Normal', 50: 'Normal', 51: 'Normal', 52: 'Normal', 53: 'Normal', 54: 'Normal', 55: 'Normal', 56: 'Normal', 57: 'Normal', 58: 'Normal', 59: 'Normal', 60: 'Normal', 61: 'Normal', 62: 'Normal', 63: 'Normal', 64: 'Normal', 65: 'Normal', 66: 'Normal', 67: 'Normal', 68: 'Normal', 69: 'Normal', 70: 'Normal', 71: 'Normal', 72: 'Normal', 73: 'Normal', 74: 'Normal', 75: 'Normal', 76: 'Normal', 77: 'Normal', 78: 'Normal', 79: 'Normal', 80: 'Normal', 81: 'Normal', 82: 'Normal', 83: 'Normal', 84: 'Normal', 85: 'Normal', 86: 'Normal', 87: 'Normal', 88: 'Normal', 89: 'Normal', 90: 'Normal', 91: 'Normal', 92: 'Normal', 93: 'Normal', 94: 'Normal', 95: 'Normal', 96: 'Normal', 97: 'Normal', 98: 'Normal', 99: 'Normal', 100: 'Normal', 101: 'Normal', 102: 'Normal', 103: 'Normal', 104: 'Normal', 105: 'Normal', 106: 'Normal', 107: 'Normal', 108: 'Normal', 109: 'Normal', 110: 'Normal', 111: 'Normal', 112: 'Normal', 113: 'Normal', 114: 'Normal', 115: 'Normal', 116: 'Normal', 117: 'Normal', 118: 'Normal', 119: 'Normal', 120: 'Normal', 121: 'Normal', 122: 'Normal', 123: 'Normal', 124: 'Normal', 125: 'Normal', 126: 'Normal', 127: 'Normal', 128: 'Normal', 129: 'Normal', 130: 'Normal', 131: 'Normal', 132: 'Normal', 133: 'Normal', 134: 'Normal', 135: 'Normal', 136: 'Normal', 137: 'Normal', 138: 'Normal', 139: 'Normal', 140: 'Normal', 141: 'Normal', 142: 'Normal', 143: 'Normal', 144: 'Normal', 145: 'Normal', 146: 'Normal', 147: 'Normal', 148: 'Normal', 149: 'Normal', 150: 'Normal', 151: 'Normal', 152: 'Normal', 153: 'Normal', 154: 'Normal', 155: 'Normal', 156: 'Normal', 157: 'Normal', 158: 'Normal', 159: 'Normal', 160: 'Normal', 161: 'Normal', 162: 'Normal', 163: 'Normal', 164: 'Normal', 165: 'Normal', 166: 'Normal', 167: 'Normal', 168: 'Normal', 169: 'Normal', 170: 'Normal', 171: 'Normal', 172: 'Normal', 173: 'Normal', 174: 'Normal', 175: 'Normal', 176: 'Normal', 177: 'Normal', 178: 'Normal', 179: 'Normal', 180: 'Normal', 181: 'Normal', 182: 'Normal', 183: 'Normal', 184: 'Normal', 185: 'Normal', 186: 'Normal', 187: 'Normal', 188: 'Normal', 189: 'Normal', 190: 'Normal', 191: 'Normal', 192: 'Normal', 193: 'Normal', 194: 'Normal', 195: 'Normal', 196: 'Normal', 197: 'Normal', 198: 'Normal', 199: 'Normal', 200: 'Normal', 201: 'Normal', 202: 'Normal', 203: 'Normal', 204: 'Normal', 205: 'Normal', 206: 'Normal', 207: 'Normal', 208: 'Normal', 209: 'Normal', 210: 'Normal', 211: 'Normal', 212: 'Normal', 213: 'Normal', 214: 'Normal', 215: 'Normal', 216: 'Normal', 217: 'Normal', 218: 'Normal', 219: 'Normal', 220: 'Normal', 221: 'Normal', 222: 'Normal', 223: 'Normal', 224: 'Normal', 225: 'Normal', 226: 'Normal', 227: 'Normal', 228: 'Normal', 229: 'Normal', 230: 'Normal', 231: 'Normal', 232: 'Normal', 233: 'Normal', 234: 'Normal', 235: 'Normal', 236: 'Normal', 237: 'Normal', 238: 'Normal', 239: 'Normal', 240: 'Normal', 241: 'Normal', 242: 'Normal', 243: 'Normal', 244: 'Normal', 245: 'Normal', 246: 'Normal', 247: 'Normal', 248: 'Normal', 249: 'Normal', 250: 'Normal', 251: 'Normal', 252: 'Normal', 253: 'Normal', 254: 'Normal', 255: 'Normal', 256: 'Normal', 257: 'Normal', 258: 'Normal', 259: 'Normal', 260: 'Normal', 261: 'Normal', 262: 'Normal', 263: 'Normal', 264: 'Normal', 265: 'Normal', 266: 'Normal', 267: 'Normal', 268: 'Normal', 269: 'Normal', 270: 'Normal', 271: 'Normal', 272: 'Normal', 273: 'Normal', 274: 'Normal', 275: 'Normal', 276: 'Normal', 277: 'Normal', 278: 'Normal', 279: 'Normal', 280: 'Normal', 281: 'Normal', 282: 'Normal', 283: 'Normal', 284: 'Normal', 285: 'Normal', 286: 'Normal', 287: 'Normal', 288: 'Normal', 289: 'Normal', 290: 'Normal', 291: 'Normal', 292: 'Normal', 293: 'Normal', 294: 'Normal', 295: 'Normal', 296: 'Normal', 297: 'Normal', 298: 'Normal', 299: 'Normal', 300: 'Normal', 301: 'Normal', 302: 'Normal', 303: 'Normal', 304: 'Normal', 305: 'Normal', 306: 'Normal', 307: 'Normal', 308: 'Normal', 309: 'Normal', 310: 'Normal', 311: 'Normal', 312: 'Normal', 313: 'Normal', 314: 'Normal', 315: 'Normal', 316: 'Normal', 317: 'Normal', 318: 'Normal', 319: 'Normal', 320: 'Normal', 321: 'Normal', 322: 'Normal', 323: 'Normal', 324: 'Normal', 325: 'Normal', 326: 'Normal', 327: 'Normal', 328: 'Normal', 329: 'Normal', 330: 'Normal', 331: 'Normal', 332: 'Normal', 333: 'Normal', 334: 'Normal', 335: 'Normal', 336: 'Normal', 337: 'Normal', 338: 'Normal', 339: 'Normal', 340: 'Normal', 341: 'Normal', 342: 'Normal', 343: 'Normal', 344: 'Normal', 345: 'Normal', 346: 'Normal', 347: 'Normal', 348: 'Normal', 349: 'Normal', 350: 'Normal', 351: 'Normal', 352: 'Normal', 353: 'Normal', 354: 'Normal', 355: 'Normal', 356: 'Normal', 357: 'Normal', 358: 'Normal', 359: 'Normal', 360: 'Normal', 361: 'Normal', 362: 'Normal', 363: 'Normal', 364: 'Normal', 365: 'Normal', 366: 'Normal', 367: 'Normal', 368: 'Normal', 369: 'Normal', 370: 'Normal', 371: 'Normal', 372: 'Normal', 373: 'Normal', 374: 'Normal', 375: 'Normal', 376: 'Normal', 377: 'Normal', 378: 'Normal', 379: 'Normal', 380: 'Normal', 381: 'Normal', 382: 'Normal', 383: 'Normal', 384: 'Normal', 385: 'Normal', 386: 'Normal', 387: 'Normal', 388: 'Normal', 389: 'Normal', 390: 'Normal', 391: 'Normal', 392: 'Normal', 393: 'Normal', 394: 'Normal', 395: 'Normal', 396: 'Normal', 397: 'Normal', 398: 'Normal', 399: 'Normal', 400: 'Normal', 401: 'Normal', 402: 'Normal', 403: 'Normal', 404: 'Normal', 405: 'Normal', 406: 'Normal', 407: 'Normal', 408: 'Normal', 409: 'Normal', 410: 'Normal', 411: 'Normal', 412: 'Normal', 413: 'Normal', 414: 'Normal', 415: 'Normal', 416: 'Normal', 417: 'Normal', 418: 'Normal', 419: 'Normal', 420: 'Normal', 421: 'Normal', 422: 'Normal', 423: 'Normal', 424: 'Normal', 425: 'Normal', 426: 'Normal', 427: 'Normal', 428: 'Normal', 429: 'Normal', 430: 'Normal', 431: 'Normal', 432: 'Normal', 433: 'Normal', 434: 'Normal', 435: 'Normal', 436: 'Normal', 437: 'Normal', 438: 'Normal', 439: 'Normal', 440: 'Normal', 441: 'Normal', 442: 'Normal', 443: 'Normal', 444: 'Normal', 445: 'Normal', 446: 'Normal', 447: 'Normal', 448: 'Normal', 449: 'Normal', 450: 'Normal', 451: 'Normal', 452: 'Normal', 453: 'Normal', 454: 'Normal', 455: 'Normal', 456: 'Normal', 457: 'Normal', 458: 'Normal', 459: 'Normal', 460: 'Normal', 461: 'Normal', 462: 'Normal', 463: 'Normal', 464: 'Normal', 465: 'Normal', 466: 'Normal', 467: 'Normal', 468: 'Normal', 469: 'Normal', 470: 'Normal', 471: 'Normal', 472: 'Normal', 473: 'Normal', 474: 'Normal', 475: 'Normal', 476: 'Normal', 477: 'Normal', 478: 'Normal', 479: 'Normal', 480: 'Normal', 481: 'Normal', 482: 'Normal', 483: 'Normal', 484: 'Normal', 485: 'Normal', 486: 'Normal', 487: 'Normal', 488: 'Normal', 489: 'Normal', 490: 'Normal', 491: 'Normal', 492: 'Normal', 493: 'Normal', 494: 'Normal', 495: 'Normal', 496: 'Normal', 497: 'Normal', 498: 'Normal', 499: 'Normal', 500: 'Normal', 501: 'Normal', 502: 'Normal', 503: 'Normal', 504: 'Normal', 505: 'Normal', 506: 'Normal', 507: 'Normal', 508: 'Normal', 509: 'Normal', 510: 'Normal', 511: 'Normal', 512: 'Normal', 513: 'Normal', 514: 'Normal', 515: 'Normal', 516: 'Normal', 517: 'Normal', 518: 'Normal', 519: 'Normal', 520: 'Normal', 521: 'Normal', 522: 'Normal', 523: 'Normal', 524: 'Normal', 525: 'Normal', 526: 'Normal', 527: 'Normal', 528: 'Normal', 529: 'Normal', 530: 'Normal', 531: 'Normal', 532: 'Normal', 533: 'Normal', 534: 'Normal', 535: 'Normal', 536: 'Normal', 537: 'Normal', 538: 'Normal', 539: 'Normal', 540: 'Normal', 541: 'Normal', 542: 'Normal', 543: 'Normal', 544: 'Normal', 545: 'Normal', 546: 'Normal', 547: 'Normal', 548: 'Normal', 549: 'Normal', 550: 'Normal', 551: 'Normal', 552: 'Normal', 553: 'Normal', 554: 'Normal', 555: 'Normal', 556: 'Normal', 557: 'Normal', 558: 'Normal', 559: 'Normal', 560: 'Normal', 561: 'Normal', 562: 'Normal', 563: 'Normal', 564: 'Normal', 565: 'Normal', 566: 'Normal', 567: 'Normal', 568: 'Normal', 569: 'Normal', 570: 'Normal', 571: 'Normal', 572: 'Normal', 573: 'Normal', 574: 'Normal', 575: 'Normal', 576: 'Normal', 577: 'Normal', 578: 'Normal', 579: 'Normal', 580: 'Normal', 581: 'Normal', 582: 'Normal', 583: 'Normal', 584: 'Normal', 585: 'Normal', 586: 'Normal', 587: 'Normal', 588: 'Normal', 589: 'Normal', 590: 'Normal', 591: 'Normal', 592: 'Normal', 593: 'Normal', 594: 'Normal', 595: 'Normal', 596: 'Normal', 597: 'Normal', 598: 'Normal', 599: 'Normal', 600: 'Normal', 601: 'Normal', 602: 'Normal', 603: 'Normal', 604: 'Normal', 605: 'Normal', 606: 'Normal', 607: 'Normal', 608: 'Normal', 609: 'Normal', 610: 'Normal', 611: 'Normal', 612: 'Normal', 613: 'Normal', 614: 'Normal', 615: 'Normal', 616: 'Normal', 617: 'Normal', 618: 'Normal', 619: 'Normal', 620: 'Normal', 621: 'Normal', 622: 'Normal', 623: 'Normal', 624: 'Normal', 625: 'Normal', 626: 'Normal', 627: 'Normal', 628: 'Normal', 629: 'Normal', 630: 'Normal', 631: 'Normal', 632: 'Normal', 633: 'Normal', 634: 'Normal', 635: 'Normal', 636: 'Normal', 637: 'Normal', 638: 'Normal', 639: 'Normal', 640: 'Normal', 641: 'Normal', 642: 'Normal', 643: 'Normal', 644: 'Normal', 645: 'Normal', 646: 'Normal', 647: 'Normal', 648: 'Normal', 649: 'Normal', 650: 'Normal', 651: 'Normal', 652: 'Normal', 653: 'Normal', 654: 'Normal', 655: 'Normal', 656: 'Normal', 657: 'Normal', 658: 'Normal', 659: 'Normal', 660: 'Normal', 661: 'Normal', 662: 'Normal', 663: 'Normal', 664: 'Normal', 665: 'Normal', 666: 'Normal', 667: 'Normal', 668: 'Normal', 669: 'Normal', 670: 'Normal', 671: 'Normal', 672: 'Normal', 673: 'Normal', 674: 'Normal', 675: 'Normal', 676: 'Normal', 677: 'Normal', 678: 'Normal', 679: 'Normal', 680: 'Normal', 681: 'Normal', 682: 'Normal', 683: 'Normal', 684: 'Normal', 685: 'Normal', 686: 'Normal', 687: 'Normal', 688: 'Normal', 689: 'Normal', 690: 'Normal', 691: 'Normal', 692: 'Normal', 693: 'Normal', 694: 'Normal', 695: 'Normal', 696: 'Normal', 697: 'Normal', 698: 'Normal', 699: 'Normal', 700: 'Normal', 701: 'Normal', 702: 'Normal', 703: 'Normal', 704: 'Normal', 705: 'Normal', 706: 'Normal', 707: 'Normal', 708: 'Normal', 709: 'Normal', 710: 'Normal', 711: 'Normal', 712: 'Normal', 713: 'Normal', 714: 'Normal', 715: 'Normal', 716: 'Normal', 717: 'Normal', 718: 'Normal', 719: 'Normal', 720: 'Normal', 721: 'Normal', 722: 'Normal', 723: 'Normal', 724: 'Normal', 725: 'Normal', 726: 'Normal', 727: 'Normal', 728: 'Normal', 729: 'Normal', 730: 'Normal', 731: 'Normal', 732: 'Normal', 733: 'Normal', 734: 'Normal', 735: 'Normal', 736: 'Normal', 737: 'Normal', 738: 'Normal', 739: 'Normal', 740: 'Normal', 741: 'Normal', 742: 'Normal', 743: 'Normal', 744: 'Normal', 745: 'Normal', 746: 'Normal', 747: 'Normal', 748: 'Normal', 749: 'Normal', 750: 'Normal', 751: 'Normal', 752: 'Normal', 753: 'Normal', 754: 'Normal', 755: 'Normal', 756: 'Normal', 757: 'Normal', 758: 'Normal', 759: 'Normal', 760: 'Normal', 761: 'Normal', 762: 'Normal', 763: 'Normal', 764: 'Normal', 765: 'Normal', 766: 'Normal', 767: 'Normal', 768: 'Normal', 769: 'Normal', 770: 'Normal', 771: 'Normal', 772: 'Normal', 773: 'Normal', 774: 'Normal', 775: 'Normal', 776: 'Normal', 777: 'Normal', 778: 'Normal', 779: 'Normal', 780: 'Normal', 781: 'Normal', 782: 'Normal', 783: 'Normal', 784: 'Normal', 785: 'Normal', 786: 'Normal', 787: 'Normal', 788: 'Normal', 789: 'Normal', 790: 'Normal', 791: 'Normal', 792: 'Normal', 793: 'Normal', 794: 'Normal', 795: 'Normal', 796: 'Normal', 797: 'Normal', 798: 'Normal', 799: 'Normal', 800: 'Normal', 801: 'Normal', 802: 'Normal', 803: 'Normal', 804: 'Normal', 805: 'Normal', 806: 'Normal', 807: 'Normal', 808: 'Normal', 809: 'Normal', 810: 'Normal', 811: 'Normal', 812: 'Normal', 813: 'Normal', 814: 'Normal', 815: 'Normal', 816: 'Normal', 817: 'Normal', 818: 'Normal', 819: 'Normal', 820: 'Normal', 821: 'Normal', 822: 'Normal', 823: 'Normal', 824: 'Normal', 825: 'Normal', 826: 'Normal', 827: 'Normal', 828: 'Normal', 829: 'Normal', 830: 'Normal', 831: 'Normal', 832: 'Normal', 833: 'Normal', 834: 'Normal', 835: 'Normal', 836: 'Normal', 837: 'Normal', 838: 'Normal', 839: 'Normal', 840: 'Normal', 841: 'Normal', 842: 'Normal', 843: 'Normal', 844: 'Normal', 845: 'Normal', 846: 'Normal', 847: 'Normal', 848: 'Normal', 849: 'Normal', 850: 'Normal', 851: 'Normal', 852: 'Normal', 853: 'Normal', 854: 'Normal', 855: 'Normal', 856: 'Normal', 857: 'Normal', 858: 'Normal', 859: 'Normal', 860: 'Normal', 861: 'Normal', 862: 'Normal', 863: 'Normal', 864: 'Normal', 865: 'Normal', 866: 'Normal', 867: 'Normal', 868: 'Normal', 869: 'Normal', 870: 'Normal', 871: 'Normal', 872: 'Normal', 873: 'Normal', 874: 'Normal', 875: 'Normal', 876: 'Normal', 877: 'Normal', 878: 'Normal', 879: 'Normal', 880: 'Normal', 881: 'Normal', 882: 'Normal', 883: 'Normal', 884: 'Normal', 885: 'Normal', 886: 'Normal', 887: 'Normal', 888: 'Normal', 889: 'Normal', 890: 'Normal', 891: 'Normal', 892: 'Normal', 893: 'Normal', 894: 'Normal', 895: 'Normal', 896: 'Normal', 897: 'Normal', 898: 'Normal', 899: 'Normal', 900: 'Normal', 901: 'Normal', 902: 'Normal', 903: 'Normal', 904: 'Normal', 905: 'Normal', 906: 'Normal', 907: 'Normal', 908: 'Normal', 909: 'Normal', 910: 'Normal', 911: 'Normal', 912: 'Normal', 913: 'Normal', 914: 'Normal', 915: 'Normal', 916: 'Normal', 917: 'Normal', 918: 'Normal', 919: 'Normal', 920: 'Normal', 921: 'Normal', 922: 'Normal', 923: 'Normal', 924: 'Normal', 925: 'Normal', 926: 'Normal', 927: 'Normal', 928: 'Normal', 929: 'Normal', 930: 'Normal', 931: 'Normal', 932: 'Normal', 933: 'Normal', 934: 'Normal', 935: 'Normal', 936: 'Normal', 937: 'Normal', 938: 'Normal', 939: 'Normal', 940: 'Normal', 941: 'Normal', 942: 'Normal', 943: 'Normal', 944: 'Normal', 945: 'Normal', 946: 'Normal', 947: 'Normal', 948: 'Normal', 949: 'Normal', 950: 'Normal', 951: 'Normal', 952: 'Normal', 953: 'Normal', 954: 'Normal', 955: 'Normal', 956: 'Normal', 957: 'Normal', 958: 'Normal', 959: 'Normal', 960: 'Normal', 961: 'Normal', 962: 'Normal', 963: 'Normal', 964: 'Normal', 965: 'Normal', 966: 'Normal', 967: 'Normal', 968: 'Normal', 969: 'Normal', 970: 'Normal', 971: 'Normal', 972: 'Normal', 973: 'Normal', 974: 'Normal', 975: 'Normal', 976: 'Normal', 977: 'Normal', 978: 'Normal', 979: 'Normal', 980: 'Normal', 981: 'Normal', 982: 'Normal', 983: 'Normal', 984: 'Normal', 985: 'Normal', 986: 'Normal', 987: 'Normal', 988: 'Normal', 989: 'Normal', 990: 'Normal', 991: 'Normal', 992: 'Normal', 993: 'Normal', 994: 'Normal', 995: 'Normal', 996: 'Normal', 997: 'Normal', 998: 'Normal', 999: 'Normal'}

## Parte 7 — Resumen automático

Cree una función llamada `generar_resumen(registros)` que retorne un diccionario con:

- `total_registros`
- `registros_validos_potencia`
- `potencia_promedio`
- `temperatura_promedio`
- `cantidad_alertas`
- `cantidad_precauciones`
- `cantidad_normales`

In [12]:
def generar_resumen(registros):

    total_registros = len(registros)#Total de registros
    potencias = [
        regis["potencia"]
        for regis in registros
        if regis["potencia"] is not None
    ]
    temperaturas = [
        regis["temperatura"]
        for regis in registros
        if regis["temperatura"] is not None
    ]


    potencia_promedio = (sum(potencias) / len(potencias) if len(potencias) > 0 else 0)
    temperatura_promedio = ( sum(temperaturas) / len(temperaturas) if len(temperaturas) > 0 else 0 )

    estados = [regis["estado_temperatura"] for regis in registros]

    resumen = {
        "total_registros": total_registros,
        "registros_validos_potencia": len(potencias),
        "potencia_promedio": potencia_promedio,
        "temperatura_promedio": temperatura_promedio,
        "cantidad_alertas": estados.count("Alerta"),
        "cantidad_precauciones": estados.count("Precaución"),
        "cantidad_normales": estados.count("Normal"),
    }

    return resumen

resumen = generar_resumen(registros_limpios)
print(resumen)

{'total_registros': 1000, 'registros_validos_potencia': 1000, 'potencia_promedio': 48.29996716520532, 'temperatura_promedio': 20.161157833395325, 'cantidad_alertas': 0, 'cantidad_precauciones': 0, 'cantidad_normales': 1000}

## Parte 8 — Visualización como tabla

Convierta `registros_limpios` en un `DataFrame` de Pandas.

In [15]:
df = pd.DataFrame(registros_limpios)

# Para visualizar la tabla en pantalla:
df

      id  voltaje  corriente  temperatura   potencia estado_temperatura
0      0     24.0   1.932482    20.397371  46.379572             Normal
1      1     24.0   1.995546    19.989382  47.893111             Normal
2      2     24.0   1.940743    20.718098  46.577837             Normal
3      3     24.0   1.999154    21.518244  47.979693             Normal
4      4     24.0   1.850520    20.212251  44.412483             Normal
..   ...      ...        ...          ...        ...                ...
995  995     24.0   2.302904    24.113340  55.269700             Normal
996  996     24.0   2.318978    25.825217  55.655472             Normal
997  997     24.0   2.166748    24.946835  52.001942             Normal
998  998     24.0   2.321739    24.022537  55.721734             Normal
999  999     24.0   2.269873    24.981074  54.476945             Normal

[1000 rows x 6 columns]

## Parte 9 — Buenas prácticas

Revise su notebook y verifique:

- Los nombres de variables son claros.
- Las funciones tienen una tarea específica.
- El código no está repetido innecesariamente.
- Las celdas están ejecutadas en orden.
- Hay explicaciones en texto.

## Parte 10 — Repositorio inicial en GitHub

Cree un repositorio en GitHub con el nombre:

**analisis-datos-python-apellido-nombre**

Estructura mínima esperada:

```text
analisis-datos-python-apellido-nombre/
│
├── README.md
├── requirements.txt
├── notebooks/
│   ├── semana_02_introduccion.ipynb
│   ├── semana_03_fundamentos_python.ipynb
│   └── semana_04_funciones_modularizacion.ipynb
│
├── data/
│   ├── raw/
│   └── processed/
│
├── src/
│   └── funciones.py
│
└── reports/
    └── figuras/
```

**Enlace al repositorio:**  
https://github.com/Karen140215/analisis-datos-python-Karen-Garcia

## Parte 11 — Reflexión final

Responda:

1. ¿Qué ventaja tuvo usar funciones en el procesamiento de los registros?
2. ¿Por qué es importante manejar errores antes de analizar datos?
3. ¿Qué función del taller considera más útil?
4. ¿Qué elemento del repositorio ayuda más a la reproducibilidad?

**Respuesta:**  
1. ¿Qué ventaja tuvo usar funciones en el procesamiento de los registros?

Una ventaja importante fue que no tuve que repetir el mismo código para cada registro. Por ejemplo, hice las funciones convertir a float, calcular la potencia y clasificar temperatura, y después las utilicé con los datos del dataset. Esto hizo que el código fuera más organizado y fácil de entender. También, si encontraba algún error podía corregirlo directamente en la función sin tener que cambiar varias partes del código.

2. ¿Por qué es importante manejar errores antes de analizar datos?

Es importante porque los datos pueden tener valores que no son correctos o que vienen escritos de una forma diferente. En este caso, por ejemplo había un "error" en la columna de corriente. Si no se arreglaba ese dato, podía causar problemas al hacer los cálculos. Por eso, con la funcion convertir a float se revisaron los valores y los que no eran válidos se tomaron como None, para asi  poder identificarlos y no usarlos en los cálculos.

3. ¿Qué función del taller considera más útil?

Considero que la función generar resumen fue la más útil porque permite tener una visión general de los datos. En lugar de revisar los 1000 registros uno por uno esta función ayuda a obtener información como promedios, totales y cantidad de estados. Me parece útil porque facilita la interpretación de todos los resultados.

4. ¿Qué elemento del repositorio ayuda más a la reproducibilidad?

Para mí, el archivo requirements es el que más ayuda porque deja registradas las librerías que se utilizaron en el proyecto. Así otra persona puede instalar esas mismas dependencias y ejecutar el código sin tener que buscar una por una qué librerías hacen falta. También facilita volver a trabajar en el proyecto después de un tiempo.